In [1]:
import numpy as np

In [2]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [4]:
#to print individual elements by using flatten function
for cell in a.flatten():
   print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [5]:
#to prpint each elememts by using nditer   
for x in np.nditer(a,order='F',flags=['external_loop']): #we use C order inorder to go row by row, inorder to go col by col we use Fortran(F) order
   print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [6]:
#Modify array values while iterating
for x in np.nditer(a, op_flags=['readwrite']):
    x[...] = x * x

In [7]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

# Iterate two broadcastable arrays concurrently

In [8]:
b = np.arange(3, 15, 4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [9]:
for x, y in np.nditer([a,b]):
    print (x,y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11


# INITIALIZING DIFFERENT TYPE OF ARRAYS

In [10]:
np.zeros((2,3)) #to print zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((2,3),dtype='int32') #to print ones

array([[1, 1, 1],
       [1, 1, 1]])

In [12]:
#print any other number
np.full((2,2),3) 

array([[3, 3],
       [3, 3]])

In [13]:
#to print random decimal number
np.random.rand(4,2)

array([[0.45574069, 0.93252243],
       [0.03702555, 0.8982581 ],
       [0.42178105, 0.12466041],
       [0.4086993 , 0.99804696]])

In [16]:
#to get random integre values
np.random.randint(7,size=(3,3))

array([[4, 5, 3],
       [1, 1, 1],
       [1, 4, 3]])

In [15]:
#to form identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
#to repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [18]:
#see the question present in cw after application
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1]=9
print(z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# copying the array

In [19]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


# MATHEMATICS

In [20]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [21]:
a + 2

array([3, 4, 5, 6])

In [22]:
a - 2

array([-1,  0,  1,  2])

In [25]:
a * 2

array([2, 4, 6, 8])

In [24]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [26]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [27]:
a ** 2

array([ 1,  4,  9, 16])

In [28]:
# Take the sin
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

# LINEAR ALGEBRA

In [29]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [30]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

# STATISTICS

In [34]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
np.min(stats)

1

In [33]:
np.max(stats, axis=1) #so it basically provides the maximun number present in each row

array([3, 6])

In [35]:
np.sum(stats, axis=0) #provides the sum of each col

array([5, 7, 9])

# Reorganizing array

In [36]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [38]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [39]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])